
<div id="footer">
	
	<ul id="footermenu">
	<li><a href="/" title="">home</a></li>
	<li><a href="/about" title="">about</a></li>
	<li><a href="/map/" title="">map</a></li>
	<li><a href="/inventory/" title="">inventory</a></li>
	<li><a href="/data/" title="">data</a></li>
	<li><a href="http://blog.tektonomastics.org/" title="">blog</a></li>
	<li><a href="mailto:tektonomastics@gmail.com" title="">contact</a></li>
	
	</ul>
	</div>

	
	
	