
<div id="footer">
	
	<ul id="footermenu">
	<li><a href="http://tektonomastics.org/" title="">home</a></li>
	<li><a href="http://blog.tektonomastics.org/post/632177458/about" title="">about</a></li>
	<li><a href="http://tektonomastics.org/map/" title="">map</a></li>
	<li><a href="http://tektonomastics.org/inventory/" title="">inventory</a></li>
	<li><a href="http://blog.tektonomastics.org/" title="">blog</a></li>
	<li><a href="mailto:tektonomastics@gmail.com" title="">contact</a></li>
	
	</ul>
	</div>

	
	
	