
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="author" content="frank">
<link rel="shortcut icon" href="http://25.media.tumblr.com/avatar_90f19417f126_16.png"/>

<LINK href="http://tektonomastics.org/style.css" rel="stylesheet" type="text/css"></LINK>
	
<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />

<script type="text/javascript" src="http://tektonomastics.org/lib/jquery-1.4.2.js"></script>

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-17298396-1']);
  _gaq.push(['_setDomainName', '.tektonomastics.org']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
