<div id="navigation">
	<ul id="menuitems">
	<li id="about"><a href="http://blog.tektonomastics.org/post/632177458/about" title=""><span>About</span></a></li>
	<li id="map"><a <?php if (strpos($_SERVER['PHP_SELF'], 'map.php')) echo 'class="currentmap"';?> href="http://tektonomastics.org/map/" title=""><span>Map</span></a></li>
	<li id="inventory"><a <?php if (strpos($_SERVER['PHP_SELF'], 'inventory.php')) echo 'class="currentinventory"';?> href="http://tektonomastics.org/inventory/" title=""><span>Inventory</span></a></li>
	<li id="blog"><a href="http://blog.tektonomastics.org/" title=""><span>Blog</span></a></li>
	</ul>
</div>